# This file was auto-generated by libretiny/generate_components.py
# Do not modify its contents.

from esphome.components.libretiny.const import FAMILY_LN882H

LN882X_BOARDS = {
    "ln-02": {
        "name": "LN-02 Wi-Fi/Ble Module",
        "family": FAMILY_LN882H,
    },
}

LN882X_BOARD_PINS = {
    "ln-02": {
        "WIRE0_SCL_0": 11,
        "WIRE0_SCL_1": 19,
        "WIRE0_SCL_2": 3,
        "WIRE0_SCL_3": 24,
        "WIRE0_SCL_4": 2,
        "WIRE0_SCL_5": 25,
        "WIRE0_SCL_6": 1,
        "WIRE0_SCL_7": 0,
        "WIRE0_SDA_0": 11,
        "WIRE0_SDA_1": 19,
        "WIRE0_SDA_2": 3,
        "WIRE0_SDA_3": 24,
        "WIRE0_SDA_4": 2,
        "WIRE0_SDA_5": 25,
        "WIRE0_SDA_6": 1,
        "WIRE0_SDA_7": 0,
        "SERIAL0_RX": 24,
        "SERIAL0_TX": 25,
        "SERIAL1_RX": 3,
        "SERIAL1_TX": 2,
        "ADC2": 0,
        "ADC3": 1,
        "ADC5": 19,
        "P0": 0,
        "P1": 1,
        "P2": 2,
        "P3": 3,
        "P11": 11,
        "P19": 19,
        "P24": 24,
        "P25": 25,
        "RX0": 24,
        "RX1": 3,
        "TX0": 25,
        "TX1": 2,
        "D0": 11,
        "D1": 19,
        "D2": 3,
        "D3": 24,
        "D4": 2,
        "D5": 25,
        "D6": 1,
        "D7": 0,
        "A2": 0,
        "A3": 1,
    },
}

BOARDS = LN882X_BOARDS
